# Generated by Django 4.2.3 on 2023-08-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_category_subscribers_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
